GET http://localhost:8080/pet/0
Content-Type: application/json

{
  "token": -1864351555545054234
}

###

POST http://localhost:8080/pet/0
Content-Type: application/json

{
  "token": -1864351555545054234,
  "name": "test",
  "status": "sold"
}

###

DELETE http://localhost:8080/pet/0
Content-Type: application/json

{
  "token": -1864351555545054234
}

###

POST http://localhost:8080/pet/0/uploadImage
Content-Type: application/json

{
  "token": -1864351555545054234,
  "petPhotoUrl": "http://test.com/test/test.img"
}

###

POST http://localhost:8080/pet
Content-Type: application/json

{
  "token": -1864351555545054234,
  "pet": {
    "id": 0,
    "category": {
      "id": 0,
      "name": "string"
    },
    "name": "doggie",
    "photoUrls": [
      "string"
    ],
    "tags": [
      {
        "id": 0,
        "name": "string"
      }
    ],
    "status": "available"
  }
}

###

PUT http://localhost:8080/pet
Content-Type: application/json

{
  "token": -1864351555545054234,
  "pet": {
    "id": 0,
    "category": {
      "id": 0,
      "name": "dog"
    },
    "name": "doggie",
    "photoUrls": [
      "string"
    ],
    "tags": [
      {
        "id": 0,
        "name": "string"
      }
    ],
    "status": "available"
  }
}

###

GET http://localhost:8080/pet/findByStatus
Content-Type: application/json

{
  "token": -1864351555545054234,
  "status": "available"
}

###